### PR TITLE
Update to Unicode 12.0.0

### PR DESCRIPTION
**Pull request by dscorbett**

### CODE REVIEW

**Comment by grigorig** [comment]
Thanks for update. I think the unit tests should be updated, but I'll do that as a follow-up.

**Comment by grigorig** [comment]
I actually noticed that the Unicode 11.0.0 update omitted some of the new scripts in the header! I'll have to fix that first and that will require a rebase of your branch.

**Comment by grigorig** [comment]
I have pushed the fixups for Unicode 11.0.0. Please rebase your branch and make sure to update the script list for Unicode 12.0.0. I'd also appreciate it if you could add script tests for the new scripts. See my commits just now for reference.

**Comment by dscorbett** [comment]
It should be all set now.

**Comment by grigorig** [comment]
LGTM.

**Pull request merged**
